# version: "3"
# services:
#   api:
#     build: .
#     image: appliy/fastapi-docker
#     ports:
#       - 8000:8000
#     volumes:
#       - ./:/app
#     # env_file:
#     #     - ./.env
#     environment:
#       - DATABASE_PORT=5432
#       - DATABASE_USER=postgres
#       - DATABASE_PASSWORD=/.,asd][p123
#       - DATABASE_HOST=postgres
#       - DATABASE_NAME=fastapi
#       - SECRET_KEY=AASDNOdjska12ksaljd1920zxduJKSAiqwhsad
#       - ALGORITHM=HS256
#       - ACCESS_TOKEN_EXPIRE_MINUTES=30
#     command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
#     depends_on:
#       - postgres

#   postgres:
#     image: postgres
#     environment:
#       - POSTGRES_PASSWORD=/.,asd][p123
#       - POSTGRES_DB=fastapi
#     volumes:
#       - postgres-db:/var/lib/postgresql/data

# volumes:
#   postgres-db:

version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
