"""User - phone number field

Revision ID: f580b51b439f
Revises: 8211d0294101
Create Date: 2023-03-18 22:51:35.720048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f580b51b439f"
down_revision = "8211d0294101"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["phone_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
